server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://49.233.171.234:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: X292322746
  redis:
  # redis 单击单实例
    password: X147852
    database: 1
    host: 49.233.171.234
    port: 6379
    #redis 哨兵模式
#    database: 1
#    password: joker
#    sentinel:
#      nodes: 192.168.44.128:26379,192.168.44.129:26379,192.168.44.130:26379
#      master: joker-master

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl