############################################################
#
#  配置数据源信息
#
############################################################
spring:
  datasource:                                              # 数据源的相关配置
    type:  com.zaxxer.hikari.HikariDataSource             # 数据源类型：HikariCP
    driver-class-name:  com.mysql.jdbc.Driver             #  mysql驱动
    url: jdbc:mysql://49.233.171.234:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: X292322746
#  elasticsearch:
#    rest:
#      uris: http://192.68.44.128:9200
#      username: es-node1
#      password:
  data:
    elasticsearch:
      cluster-name: es6
      cluster-nodes: 192.168.44.128:9300